---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: pages/documents
  label: pages
  create: all
  match: "**/*"
  templates:
  - knowledge-center
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll serve --drafts --unpublished --future -d _site
    --host 0.0.0.0 --port 8080
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --incremental --drafts --unpublished
    --future --port 8080 --host 0.0.0.0 -d _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: starefossen/ruby-node:latest
  mount_path: "/usr/src/app"
  working_dir: "/usr/src/app"
